### ISSUE TITLE
`3.0-dotnet3-core-tools` image is built using .NET 5

### ISSUE THREAD

**Issue by Erikvl87** [Azure/azure-functions-docker#518] opened 2021-10-05 08:38 UTC
We're using the `3.0-dotnet3-core-tools` image in our pipeline to build and publish a .NET 3 Azure functions app. This suddenly stopped building 4 days ago with the following error: `The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.`

It looks like the  `3.0-dotnet3-core-tools` image is now built with .NET SDK 5 while the image name suggests it should be built against .NET 3x.

Probable cause: https://github.com/Azure/azure-functions-docker/blame/8ec217d078e42e5ad74e1bb9d57dd38248a93e9c/host/3.0/buster/amd64/dotnet/dotnet-inproc/dotnet-core-tools.Dockerfile#L6

Extended log:
```
+ func azure functionapp publish $AZURE_FUNCTION_NAME --csharp
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  Restored /opt/atlassian/pipelines/agent/build/src/[**redacted**].csproj (in 2.23 sec).
  Restored /opt/atlassian/pipelines/agent/build/src/[**redacted**].csproj (in 2.87 sec).
  [**redacted**] -> /opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/bin/publish/[**redacted**].dll
  [**redacted**].AzureFunctions -> /opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/bin/publish/[**redacted**].AzureFunctions.dll
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : It was not possible to find any compatible framework version [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - The following frameworks were found: [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :       5.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App] [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : You can resolve the problem by installing the specified framework and/or SDK. [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : The specified framework can be found at: [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64 [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error :  [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
/root/.nuget/packages/microsoft.net.sdk.functions/3.0.13/build/Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : Metadata generation failed. [/opt/atlassian/pipelines/agent/build/src/[**redacted**].AzureFunctions/[**redacted**].AzureFunctions.csproj]
Build FAILED.
```

**Comment by ghost** [comment] 2021-10-05 10:16
Maybe a new automated test to pull down the new image and a sample build would help?

For our vscode devcontainer we pull down the 3.1. image, and then add the 5.0. SDK in a dockerfile, because we use 5.0. features but target 3.1, so this had a .net SDK but not both we needed to build

**Comment by martinpeck** [comment] 2021-10-05 13:58
It certainly feels wrong that we have a VS Code dev container that is based off of...

```
FROM mcr.microsoft.com/azure-functions/dotnet:3.0-dotnet3-core-tools
```
... but that this tag brings down a container that only has dotnet 5.0 available.

I've just performed the following steps:

STEPS:

1. Create new folder, and use `code .` to open VS Code from new folder
2. Add devcontainer files to the project, and select `Azure Functions & C# - .NET Core 3.1` as the base image

![image](https://user-images.githubusercontent.com/1524451/136037230-d963de8a-0a41-4679-b547-3659e08a5c5f.png)

3. Reopen the project within the remote container, and allow dev container to build
4. Open VS Code terminal within the dev container
5. run `dotnet --list-runtimes`

EXPECTED:

- dotnet Core 3.1 is installed

ACTUAL:

- dotnet core 5.0 is installed
- dotnet core 3.1 is not available
- 
![image](https://user-images.githubusercontent.com/1524451/136037723-8830c649-99ca-412b-acfd-01e0a85d2890.png)

**Comment by martinpeck** [comment] 2021-10-05 14:02
I suspect this recent PR is the cause https://github.com/Azure/azure-functions-docker/pull/515

**Comment by Dave-EMIS** [comment] 2021-10-05 14:46
I've worked around the issue by installing the .NET 3.1 SDK into my DockerFile and then instructing my build pipeline (ADO in my case) to do a `--pull` (as it is the same tag as before), but I'm not sure this is a long term solution.

Also you cannot build .NET 5 In Proc Azure functions, the options are 3 or 6 (preview), so it doesn't seem logical to have to install it yourself.

**Comment by CooperLink** [comment] 2021-10-05 17:50
Hello, thank you for filing this issue. Sorry for the inconvenience.  I have addressed this issue in the above commit.  We needed to update images that pulled functions-host to dotnet5.0 sdk.  Seems that these core-tools images got caught in that commit as mentioned above.  We are introducing maintainability features that should hopefully stop this type of thing from happening in the future. I will update this thread and close this issue when I have uploaded the new dotnet3-core-tools image to MCR for your dependencies.

Please let me know if you have any questions.

**Comment by CooperLink** [comment] 2021-10-05 20:06
This should be resolved now. Please rebuild your images.  I tested this locally by downloading the image from MCR and checking the runtime shown here.  Sorry again for the inconvenience. I will be introducing some features to stop this from happening again in the future.  Closing issue
![image](https://user-images.githubusercontent.com/46761504/136094853-d94dc5e4-bc1f-43f7-b7ca-86a14f37c6da.png)

**Closed as completed by CooperLink** 2021-10-05 20:06 UTC

**Comment by martinpeck** [comment] 2021-10-05 21:07
Thank you @CooperLink !

**Comment by martinpeck** [comment] 2021-10-06 07:05
I've just re-run my repro steps, and can confirm that I get the expected result

**Comment by Erikvl87** [comment] 2021-10-06 07:43
Thanks for acting quickly @CooperLink. I ran our pipeline again and everything is working as it should now.
