### ISSUE TITLE
Install Azure SDK into base python image

### ISSUE THREAD

**Issue by stefangordon** [Azure/azure-functions-docker#14] opened 2018-06-15 14:23 UTC
It would be nice to add `pip install azure` to https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/python3.6/Dockerfile

Of course it further aggravates #2 (although not sure if important)

This is comparable to what AWS does in Lambda, where 100% of the AWS SDK is available.

It also reduces lots of pain on the developer.  Packaging a function is usually not too big of a deal, but the Azure SDK is a very complex package (dependency tree) with lots of natively compiled binaries in it, it is nearly impossible to package without the complex docker based process used in the Functions CLI - and even then you end up with a very large zip and a slow packaging process.

I'm happy to make a PR and test the image/size if there is interest.

**Comment by asavaritayal** [comment] 2018-06-19 19:30
Azure Python SDK is a user dependency. We don't want to include it as part of the inbuilt image to avoid version mismatch and an increased size of the base image. 

**For local development,** the python functions base image is not used at all, so the user would still have to install the required packages on their machine using `pip`. 

**For hosting in Azure,** it is preferred that the user publishes the same package and version that they used for development and testing. The best way to do this is to have them provide a `requirements.txt`. To avoid the docker based process to obtain the correct binaries for hosting, we are going to rely on obtaining the platform specific wheels from PyPI. This is currently under investigation - https://github.com/Azure/azure-functions-python-worker/pull/142. /cc @elprans 

@lmazuel Is it safe to assume that all packages under the Azure Python SDK have universal wheels available on `PyPI` ?

**Comment by stefangordon** [comment] 2018-06-19 19:49
What if the user goes to the portal and creates a new function in the UI?  Seems they'd want them there. Or maybe that uses a template that could actually copy other packages in when created and is a different scenario.

I think CFFI was the tricky dependency, not sure if there is a workaround.

**Comment by aluong** [comment] 2018-06-19 20:43
FWIW, in the [Lambda deployment package document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html) they have this note:

> AWS Lambda includes the AWS SDK for Python (Boto 3), so you don't need to include it in your deployment package. However, if you want to use a version of Boto3 other than the one included by default, you can include it in your deployment package.

And here is what comes for free in the Lambda Python Environments:
https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by stefangordon** [comment] 2018-06-19 21:01
I suppose this issue shouldn't recommend the implementation detail but rather the scenario.  Main issue is that we don't currently see a reasonable solution for common scenarios of programmatic creation of python functions on MacOS or Windows (without installing a linux vm and docker).   

If there is some way to make Azure binaries available for common platforms that would solve this also.  Sounds like this is being investigated.

**Comment by lmazuel** [comment] 2018-06-20 20:33
If the SDK would be pre-installed would be awesome :). It's already done in some other azure product like [Azure Notebooks](https://notebooks.azure.com/). And I think lambda is right to do that.
Using the latest bundle "azure" makes sense. Note that I do a release every 6 months ish of this package, but I release way more often team packages (could be every week sometimes). So you can have a mismatch between the latest available specific Network package, and the one installed by Azure. But if people wants to install a more recent specific package and they can do it, it's awesome!

@asavaritayal Universal wheel or not should not matter, I'm not sure what you're asking? But to answer strictly your question, all are universal except EventHub/ServiceBus/IoT which uses C extensions inside. Also our main dependency cryptography is far from being universal. But all cases, you should have all the possible wheels.

**Comment by stefangordon** [comment] 2018-06-20 20:53
@lmazuel we have struggled to figure out how to get Linux packages to package into our Azure function deployment from a non-Linux machine.  Do these compile during install (crypto especially) or are you saying there are prebuilt binaries?  Any hints on how to approach that?

Right now I have to install the packages on linux to get things like `_cffi_backend.cpython-36m-x86_64-linux-gnu.so` - not sure if there is another way?

**Comment by lmazuel** [comment] 2018-06-20 21:50
Wheel is a pre-built format by design, that even why they deprecated the old one called "eggs". Exactly yo solve your problem :)
CFFI then is pre-built for Linux, see all the wheel that contains the string "manylinux1":
https://pypi.org/project/cffi/#files

As long as your "pip" is recent enough, this should automatically detect what wheel to use. In the old Functions (the one right now), pip was so old that wheel install was not available and it was a nightmare. See my SO about that:
https://stackoverflow.com/questions/43970307/azure-functions-installing-python-modules-and-extensions-on-consumption-plan/43984890#43984890

But I think all of that disappear, and pip should be super recent right?

**Comment by stefangordon** [comment] 2018-06-20 22:07
Ah - I see that pip has a --platform parameter, which means there is also probably a straightforward way for me to programmatically go find the matching Linux wheel from python code running on windows to include in a zip destined for a Linux machine.   Tx.

**Comment by elprans** [comment] 2018-06-20 22:16
> a way for me to programmatically go find the matching Linux wheel from python code running on windows to include in a zip destined for a Linux machine

I wrote a tool specifically for that: https://github.com/Azure/azure-functions-python-worker/pull/142

**Comment by stefangordon** [comment] 2018-06-21 15:59
Yes, I will have to do something similar but there are many complicating factors.  You can't really do a virtualenv from Windows because you'd end up with the wrong python binaries in it.   So you can go without a virtualenv (uses the one installed in base image then) but then when you try to use the Azure SDK you will up with some complicated namespace/module path issues because you already have an Azure folder in your site-packages installed in the base docker image for the Functions SDK.

Currently we go without a virtual env, set `sys.path.append(dirname(dirname(__file__)))` in our function, and delete the `init.py` from the Azure SDK to resolve the SDK modules.    A bit crazy.

An alternative would be to try to get prebuilt python images for linux to create a virtualenv on windows, or hack something into a fake `activate` script so the docker container creates a virtualenv (or symlink) for you.

**Comment by elprans** [comment] 2018-06-21 16:09
> So you can go without a virtualenv (uses the one installed in base image then) but then when you try to use the Azure SDK you will up with some complicated namespace/module path issues because you already have an Azure folder in your site-packages installed in the base docker image for the Functions SDK.

These issues only arise if you install the worker in development mode (`pip install -e`), which was done in some earlier docker images.  Regular install (`pip install azure-python-worker azure-sdk`) should work without a problem assuming that you unzip your function artifact over your virtualenv.

**Comment by elprans** [comment] 2018-06-21 16:11
Also the namespace issues should really be fixed on the SDK side.  There's no reason not to make `azure` a pure-namespace package on Python 3.

**Comment by stefangordon** [comment] 2018-06-21 16:22
Agreed for sure on SDK namespace issue, but may not be following entirely.  My approach would be to zip deploy a package with no virtualenv (I'd end up in the `/root/.pyenv` then based on current `start.sh` implementation).

So I would probably not have azure-python-worker since that is already in the env, instead I'd hack `sys.path` to look in `wwwroot` for the rest of my packages, namely the `Azure` SDK and its deps.

Ignoring the namespace issue, is this what you'd recommend, along with some tooling to get the right platform binaries in the first place?

I guess `start.sh` in worker could also create a virtual env into the root of `wwwroot` if one was not provided, might help in some cases.

**Comment by lmazuel** [comment] 2018-06-21 22:59
> Also the namespace issues should really be fixed on the SDK side. There's no reason not to make azure a pure-namespace package on Python 3.

Compatibility is one of them :). Currently I ship universal wheels for SDK, and what you ask is to release a py2 and a py3 wheel with different namespace packages system. 
Also, I customize the wheel to NOT have any namespaces packages information anymore (the __init__.py is empty if you install from wheel). But from sdist, you get a package_resource namespace package, which is incompatible with PEP420 (https://github.com/pypa/sample-namespace-packages/). This means assuming we move the SDK to PEP420 on Py3, it will not be a one shoot, and you break setuptools install for py3 users instantly with the first PEP420 package. I'm willing to admit that for you, that supports 3.6 only, setuptools is not important, but for the entire eco-system I can't just say setuptools is not supported anymore ([I tried](https://github.com/Azure/azure-sdk-for-python/issues/728))

I'm not sure I get all the details, because I don't see why it's complicated (I mean: I must miss something, because I trust you it's complicated :)). If you're interested in my humble opinion, we should do a meeting so you explain how I got it wrong, and see what I could do to help you.

**Comment by elprans** [comment] 2018-06-21 23:34
Yes, unfortunately setuptools `setup.py install` is broken in many-many ways and should not be used in any reasonable circumstance.  That said, I'm with you on compatibility.  The solution here would be to override the `install` cmdclass and use the `distutils` version directly, i.e:

```python
import distutils.command.install as distutils_install

...
setup(
    cmdclass={'install': distutils_install.install}
)
```

That way you would get a wheel-like install (i.e extracted files), albeit with `egg-info` metadata instead of the newer `dist-info`, but that should be fine as pip et al can cope.

`setup.py develop` is fine (`pip install -e` is just a wrapper around it).

**Comment by ahmelsayed** [comment] 2019-05-23 21:28
We're not doing this

**Closed by ahmelsayed** 2019-05-23 21:28 UTC
Labels: lang-Python
