### ISSUE TITLE
Latest docker image 4-python3.8-slim causing startup issues binding type(s) 'serviceBusTrigger, serviceBus' were not found

### ISSUE THREAD

**Issue by teebu** [Azure/azure-functions-docker#806] opened 2022-11-11 22:22 UTC
Latest docker image causing startup issues with v3 packages. Looks like the `bin` folder was removed, and its not using bin_v3?

**Dockerfile**:

Latest build not working:
```
FROM mcr.microsoft.com/azure-functions/python:4-python3.8-slim as az-function
```

note: it was working last week, and previous release version also works:

```
FROM mcr.microsoft.com/azure-functions/python:4.13.0-python3.8-slim as az-function
...
```

My host file:
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
...
```

Error:
```
fail: Host.Startup[402]
The 'my_function' function is in error: The binding type(s) 'serviceBusTrigger, serviceBus' were not found in the configured extension bundle. Please ensure the type is correct and the correct version of extension bundle is configured.
```

I am seeing the same error about missing serviceBusTrigger, serviceBus with node docker image.

```
FROM mcr.microsoft.com/azure-functions/node:4-node16
```

**Comment by janmayer** [comment] 2022-11-14 12:34
With the latest version of `mcr.microsoft.com/azure-functions/python:4-python3.9` released seemingly on 11.11. we also now get an error on startup: 

```
The binding type(s) 'cosmosDB' were not found in the configured extension bundle. Please ensure the type is correct and the correct version of extension bundle is configured.
```

It worked last week and it does work with `python:4.13.0-python3.9` as mentioned by @teebu.

**Comment by miqm** [comment] 2022-11-15 07:45
Same here. I noticed that with latest release folder `bin` was removed. could this be the cause?

more specific: this line and similar: https://github.com/Azure/azure-functions-docker/compare/4.13.0...4.14.0#diff-495a738f76af7708851f3d3dd694a38ab3c644a9e9d5518765557b08d1f6c9cbR36

**Comment by miqm** [comment] 2022-11-15 11:05
we've managed to make a workaround by creating a symlink that will replace missing bin folder
```
RUN ln -s /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/3.17.0/bin_v3/linux-x64 /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/3.17.0/bin && \
    ln -s /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.0.2/bin_v3/linux-x64 /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.0.2/bin
```

but this is a short term solution and I'd expect Microsoft will fix this ASAP

**Comment by raorugan** [comment] 2022-11-15 12:06
@pragnagopa , @amamounelsayed  for awareness

**Comment by cory-lane** [comment] 2022-11-16 15:40
Seeing this issue as well

**Comment by CooperLink** [comment] 2022-11-17 18:08
Thank you for filing this issue.  The team is investigating what is going on here. Could anyone that is experiencing this issue give me some more information about how you deploy your Function Apps? 
 I have a local repro of this issue when building a Custom Container as described here : https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=in-process%2Cbash%2Cazure-cli&pivots=programming-language-python.  But, we have not been able to reproduce this when deploying from VSCode or from Zip. Currently, we believe the impact here may be scoped to Custom Container Function apps.

**Comment by miqm** [comment] 2022-11-17 18:15
Zip deployment (on Linux plan only) uses docker image that is provided and controlled by app service team. They probably have some local cache or own container registry to avoid pulling from mcr all the time. Let's hope they will wait with refreshing their image or have good e2e tests...

And yes, in our case we use linux containers on premium plan and on aks.

**Comment by cory-lane** [comment] 2022-11-17 18:18
Custom docker image based on mcr.microsoft.com/azure-functions/python:4

Run in docker via AKS

**Comment by CooperLink** [comment] 2022-11-18 01:54
I am happy to report that we have remedied this issue with a new Function Docker image release. If you change your base image target to the version `4.14.0.3` you will receive a base image that includes the /bin directory for the extension bundles. I just verified that the node image you mentioned above has shipped with the fix at the node:4.14.0.3-node16. That should fix this issue for you, but please let me know if I can further assist you.

Tomorrow we will update the major version images such as python:4-python3.8-slim as well. I will keep this issue open until we have completed that major version deployment and I will update you when I have the major version image prepared

**Comment by cory-lane** [comment] 2022-11-18 16:25
4.14.0.3-python is working for me, thanks @CooperLink!

**Comment by miqm** [comment] 2022-11-18 16:52
@CooperLink - once you complete releasing the fix, can you share what went wrong and can we be certain similar problem will not occur in the future?

**Comment by pragnagopa** [comment] 2022-11-22 17:10
@miqm  - Fix has been released. We have captured repair item to include verifying custom containers as part of Functions Runtime releases.

**Closed as completed by pragnagopa** 2022-11-22 17:10 UTC

**Comment by miqm** [comment] 2022-11-25 08:21
@CooperLink , @pragnagopa  - just a note that it would be nice if you create a release 4.14.0.3 on this repository to indicate latest working release.
